"""
generate_glosses_js.py — Convert landmark_store/*.json → generated_glosses.js

Reads every landmark JSON, retargets to Three.js Euler angles, smooths,
decimates to 6 keyframes, then emits a JS module that can be merged into
the existing glosses.js animation library.

Usage:
    cd backend/
    python pipeline/generate_glosses_js.py [--gloss GLOSS] [--preview]

Flags:
    --gloss   Only regenerate a single gloss (for testing)
    --preview Print the generated JS to stdout instead of writing
"""
import argparse
import json
import sys
from pathlib import Path

_HERE    = Path(__file__).parent
_BACKEND = _HERE.parent
_STORE   = _BACKEND / "landmark_store"
_OUTPUT  = _BACKEND.parent / "frontend" / "src" / "avatar" / "generated_glosses.js"

sys.path.insert(0, str(_HERE))
from retarget import landmark_sequence_to_poses
from smooth   import smooth_and_decimate


def _pose_to_js(pose: dict) -> str:
    def _v(d):
        return f"R({d['x']}, {d['y']}, {d['z']})"
    return (
        f"{{ rightShoulder: {_v(pose['rightShoulder'])}, "
        f"rightElbow: {_v(pose['rightElbow'])}, "
        f"rightWrist: {_v(pose['rightWrist'])}, "
        f"leftShoulder: {_v(pose['leftShoulder'])}, "
        f"leftElbow: {_v(pose['leftElbow'])}, "
        f"leftWrist: {_v(pose['leftWrist'])} }}"
    )


def _entry_to_js(gloss: str, duration: float, poses: list) -> str:
    if not poses:
        return ""

    frames_js = ",\n      ".join(
        f"{{ t: {p['t']}, pose: {_pose_to_js(p['pose'])} }}"
        for p in poses
    )
    return f"""
  {gloss}: {{
    duration: {duration},
    frames: [
      {frames_js}
    ],
  }},"""


def generate(only_gloss: str | None = None) -> str:
    """Build the full generated_glosses.js content."""
    json_files = sorted(_STORE.glob("*.json"))

    if only_gloss:
        json_files = [f for f in json_files if f.stem.upper() == only_gloss.upper()]
        if not json_files:
            print(f"No landmark file for gloss '{only_gloss}'", file=sys.stderr)
            return ""

    entries = []
    ok = errors = 0

    for jf in json_files:
        gloss = jf.stem.upper()
        try:
            data = json.loads(jf.read_text(encoding="utf-8"))
            duration, poses = landmark_sequence_to_poses(data)

            if not poses:
                print(f"  SKIP {gloss}: no valid pose frames", file=sys.stderr)
                continue

            poses = smooth_and_decimate(poses, target=6)
            entry = _entry_to_js(gloss, duration, poses)
            if entry:
                entries.append(entry)
                ok += 1
        except Exception as e:
            print(f"  ERROR {gloss}: {e}", file=sys.stderr)
            errors += 1

    print(
        f"Generated {ok} entries ({errors} errors) → {_OUTPUT}",
        file=sys.stderr,
    )

    header = """\
// AUTO-GENERATED by pipeline/generate_glosses_js.py — do NOT edit by hand.
// Re-run:  cd backend && python pipeline/generate_glosses_js.py

const R = (x, y = 0, z = 0) => ({ x, y, z })

export const GENERATED_GLOSS_ANIMS = {"""

    footer = "\n}\n"
    return header + "".join(entries) + footer


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--gloss",   help="Only process this gloss")
    parser.add_argument("--preview", action="store_true", help="Print to stdout, don't write file")
    args = parser.parse_args()

    content = generate(only_gloss=args.gloss)
    if not content:
        sys.exit(1)

    if args.preview:
        print(content)
    else:
        _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        _OUTPUT.write_text(content, encoding="utf-8")
        print(f"Written to {_OUTPUT}")


if __name__ == "__main__":
    main()
