// AUTO-GENERATED by pipeline/generate_glosses_js.py — do NOT edit by hand.
// Re-run:  cd backend && python pipeline/generate_glosses_js.py

const R = (x, y = 0, z = 0) => ({ x, y, z })

export const GENERATED_GLOSS_ANIMS = {
  BAD: {
    duration: 9.48,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-15.8, 0.0, 5.6), rightElbow: R(-64.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-5.6, 0.0, 5.6), leftElbow: R(-90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.3, pose: { rightShoulder: R(6.8, 0.0, 7.1), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(-1.3, 0.0, 0.0), leftShoulder: R(1.0, 0.0, 8.8), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.333, pose: { rightShoulder: R(12.7, 0.0, 8.8), rightElbow: R(53.9, 0.0, 80.0), rightWrist: R(0.9, 0.0, 0.0), leftShoulder: R(5.7, 0.0, 9.6), leftElbow: R(-18.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 9.275, pose: { rightShoulder: R(8.1, 0.0, 16.6), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(10.8, 0.0, 0.0), leftShoulder: R(17.3, 0.0, 0.8), leftElbow: R(105.1, 0.0, -73.7), leftWrist: R(1.8, 0.0, 0.0) } },
      { t: 9.442, pose: { rightShoulder: R(-13.0, 0.0, 10.0), rightElbow: R(-100.1, 0.0, 80.0), rightWrist: R(-0.7, 0.0, 0.0), leftShoulder: R(-1.2, 0.0, 0.8), leftElbow: R(-28.1, 0.0, 14.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 9.476, pose: { rightShoulder: R(-15.2, 0.0, 9.3), rightElbow: R(-115.2, 0.0, 80.0), rightWrist: R(-4.8, 0.0, 0.0), leftShoulder: R(-6.3, 0.0, 1.2), leftElbow: R(-82.4, 0.0, 26.3), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  DRINK: {
    duration: 97.53,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(20.0, 0.0, 21.5), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(4.7, 0.0, 0.0), leftShoulder: R(-33.3, 0.0, 51.4), leftElbow: R(95.0, 0.0, 14.0), leftWrist: R(0.6, 0.0, 0.0) } },
      { t: 47.047, pose: { rightShoulder: R(-20.2, 0.0, 19.3), rightElbow: R(105.1, 0.0, 67.7), rightWrist: R(3.6, 0.0, 0.0), leftShoulder: R(-29.2, 0.0, 39.9), leftElbow: R(52.7, 0.0, -32.3), leftWrist: R(1.4, 0.0, 0.0) } },
      { t: 47.08, pose: { rightShoulder: R(-44.9, 0.0, 31.6), rightElbow: R(86.2, 0.0, 45.3), rightWrist: R(-6.8, 0.0, 0.0), leftShoulder: R(-56.6, 0.0, 66.9), leftElbow: R(54.8, 0.0, -21.1), leftWrist: R(4.9, 0.0, 0.0) } },
      { t: 47.214, pose: { rightShoulder: R(-37.3, 0.0, 31.3), rightElbow: R(52.7, 0.0, 30.4), rightWrist: R(-2.1, 0.0, 0.0), leftShoulder: R(-46.8, 0.0, 63.5), leftElbow: R(105.1, 0.0, -50.9), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 47.28, pose: { rightShoulder: R(-11.7, 0.0, 18.6), rightElbow: R(54.8, 0.0, 45.3), rightWrist: R(4.4, 0.0, 0.0), leftShoulder: R(-19.4, 0.0, 35.6), leftElbow: R(90.0, 0.0, -77.0), leftWrist: R(-11.9, 0.0, 0.0) } },
      { t: 97.531, pose: { rightShoulder: R(20.1, 0.0, 28.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-3.8, 0.0, 4.1), leftElbow: R(-82.4, 0.0, -80.0), leftWrist: R(14.3, 0.0, 0.0) } }
    ],
  },
  EAT: {
    duration: 97.53,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(20.0, 0.0, 21.5), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(4.7, 0.0, 0.0), leftShoulder: R(-33.3, 0.0, 51.4), leftElbow: R(95.0, 0.0, 14.0), leftWrist: R(0.6, 0.0, 0.0) } },
      { t: 47.047, pose: { rightShoulder: R(-20.2, 0.0, 19.3), rightElbow: R(105.1, 0.0, 67.7), rightWrist: R(3.6, 0.0, 0.0), leftShoulder: R(-29.2, 0.0, 39.9), leftElbow: R(52.7, 0.0, -32.3), leftWrist: R(1.4, 0.0, 0.0) } },
      { t: 47.08, pose: { rightShoulder: R(-44.9, 0.0, 31.6), rightElbow: R(86.2, 0.0, 45.3), rightWrist: R(-6.8, 0.0, 0.0), leftShoulder: R(-56.6, 0.0, 66.9), leftElbow: R(54.8, 0.0, -21.1), leftWrist: R(4.9, 0.0, 0.0) } },
      { t: 47.214, pose: { rightShoulder: R(-37.3, 0.0, 31.3), rightElbow: R(52.7, 0.0, 30.4), rightWrist: R(-2.1, 0.0, 0.0), leftShoulder: R(-46.8, 0.0, 63.5), leftElbow: R(105.1, 0.0, -50.9), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 47.28, pose: { rightShoulder: R(-11.7, 0.0, 18.6), rightElbow: R(54.8, 0.0, 45.3), rightWrist: R(4.4, 0.0, 0.0), leftShoulder: R(-19.4, 0.0, 35.6), leftElbow: R(90.0, 0.0, -77.0), leftWrist: R(-11.9, 0.0, 0.0) } },
      { t: 97.531, pose: { rightShoulder: R(20.1, 0.0, 28.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-3.8, 0.0, 4.1), leftElbow: R(-82.4, 0.0, -80.0), leftWrist: R(14.3, 0.0, 0.0) } }
    ],
  },
  FOOD: {
    duration: 91.86,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(21.5, 0.0, 20.8), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(18.8, 0.0, 7.0), leftElbow: R(76.2, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 19.853, pose: { rightShoulder: R(-57.2, 0.0, 40.6), rightElbow: R(-53.9, 0.0, -47.9), rightWrist: R(-11.5, 0.0, 0.0), leftShoulder: R(-59.5, 0.0, 81.7), leftElbow: R(-53.9, 0.0, 44.9), leftWrist: R(3.8, 0.0, 0.0) } },
      { t: 19.886, pose: { rightShoulder: R(-37.7, 0.0, 29.5), rightElbow: R(-18.7, 0.0, -16.6), rightWrist: R(-4.1, 0.0, 0.0), leftShoulder: R(-40.5, 0.0, 48.8), leftElbow: R(-18.7, 0.0, 13.2), leftWrist: R(2.8, 0.0, 0.0) } },
      { t: 19.953, pose: { rightShoulder: R(-17.5, 0.0, 18.6), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(2.0, 0.0, 0.0), leftShoulder: R(-22.3, 0.0, 22.0), leftElbow: R(18.7, 0.0, -3.2), leftWrist: R(-0.7, 0.0, 0.0) } },
      { t: 19.986, pose: { rightShoulder: R(1.3, 0.0, 9.2), rightElbow: R(53.9, 0.0, 47.9), rightWrist: R(11.0, 0.0, 0.0), leftShoulder: R(-4.0, 0.0, 4.2), leftElbow: R(53.9, 0.0, -47.9), leftWrist: R(-6.8, 0.0, 0.0) } },
      { t: 91.858, pose: { rightShoulder: R(20.4, 0.0, 3.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 7.1), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  GO: {
    duration: 9.07,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-9.4, 0.0, 6.7), rightElbow: R(-64.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(0.8, 0.0, 6.6), leftElbow: R(-67.3, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.266, pose: { rightShoulder: R(2.4, 0.0, 7.2), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(1.4, 0.0, 0.0), leftShoulder: R(4.3, 0.0, 8.7), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.3, pose: { rightShoulder: R(7.7, 0.0, 8.5), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(-0.9, 0.0, 0.0), leftShoulder: R(8.1, 0.0, 9.7), leftElbow: R(-18.7, 0.0, -80.0), leftWrist: R(-1.7, 0.0, 0.0) } },
      { t: 0.333, pose: { rightShoulder: R(12.6, 0.0, 10.0), rightElbow: R(53.9, 0.0, 80.0), rightWrist: R(-4.4, 0.0, 0.0), leftShoulder: R(12.2, 0.0, 10.8), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(-1.3, 0.0, 0.0) } },
      { t: 8.708, pose: { rightShoulder: R(-1.4, 0.0, 22.9), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(-0.0, 0.0, 0.0), leftShoulder: R(15.4, 0.0, 1.1), leftElbow: R(105.1, 0.0, -22.9), leftWrist: R(-11.2, 0.0, 0.0) } },
      { t: 9.075, pose: { rightShoulder: R(-5.4, 0.0, 6.1), rightElbow: R(-90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-2.8, 0.0, 6.0), leftElbow: R(-58.5, 0.0, -57.6), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  GOOD: {
    duration: 11.14,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-73.0, 0.0, 22.3), rightElbow: R(101.3, 0.0, -57.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-74.7, 0.0, 7.7), leftElbow: R(90.0, 0.0, 57.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.035, pose: { rightShoulder: R(-19.6, 0.0, 51.7), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(-6.1, 0.0, 0.0), leftShoulder: R(-19.6, 0.0, 50.1), leftElbow: R(18.7, 0.0, -16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.101, pose: { rightShoulder: R(-40.4, 0.0, 55.9), rightElbow: R(-18.7, 0.0, -16.6), rightWrist: R(1.7, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 77.6), leftElbow: R(-18.7, 0.0, 16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.135, pose: { rightShoulder: R(-60.0, 0.0, 59.9), rightElbow: R(-53.9, 0.0, -47.9), rightWrist: R(9.2, 0.0, 0.0), leftShoulder: R(-60.0, 0.0, 104.2), leftElbow: R(-53.9, 0.0, 47.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 3.137, pose: { rightShoulder: R(-20.3, 0.0, 28.3), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(6.8, 0.0, 0.0), leftShoulder: R(-21.4, 0.0, 41.8), leftElbow: R(3.6, 0.0, -33.0), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 11.145, pose: { rightShoulder: R(20.0, 0.0, 8.3), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.7, 0.0, 4.1), leftElbow: R(79.9, 0.0, 84.5), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  GOODBYE: {
    duration: 7.4,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(17.1, 0.0, 9.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-1.0, 0.0, 0.0), leftShoulder: R(12.0, 0.0, 9.3), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.32, pose: { rightShoulder: R(20.0, 0.0, 20.8), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-21.2, 0.0, 0.0), leftShoulder: R(3.7, 0.0, 10.0), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(-19.3, 0.0, 0.0) } },
      { t: 1.36, pose: { rightShoulder: R(20.0, 0.0, 20.7), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-21.2, 0.0, 0.0), leftShoulder: R(2.5, 0.0, 10.0), leftElbow: R(-18.7, 0.0, -80.0), leftWrist: R(-19.7, 0.0, 0.0) } },
      { t: 1.96, pose: { rightShoulder: R(20.0, 0.0, 18.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-21.3, 0.0, 0.0), leftShoulder: R(-0.3, 0.0, 10.1), leftElbow: R(-18.7, 0.0, -80.0), leftWrist: R(-20.6, 0.0, 0.0) } },
      { t: 2.0, pose: { rightShoulder: R(20.0, 0.0, 18.7), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-21.3, 0.0, 0.0), leftShoulder: R(1.9, 0.0, 10.1), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(-20.6, 0.0, 0.0) } },
      { t: 7.4, pose: { rightShoulder: R(17.3, 0.0, 13.2), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(20.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 10.6), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  HAPPY: {
    duration: 42.14,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-0.5, 0.0, 3.5), rightElbow: R(-14.5, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-3.8, 0.0, 11.9), leftElbow: R(-101.3, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.834, pose: { rightShoulder: R(-0.8, 0.0, 5.5), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(0.7, 0.0, 13.6), leftElbow: R(-28.3, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.867, pose: { rightShoulder: R(-2.2, 0.0, 5.4), rightElbow: R(-53.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-0.1, 0.0, 13.6), leftElbow: R(-66.5, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 24.224, pose: { rightShoulder: R(20.0, 0.0, 2.9), rightElbow: R(90.0, 0.0, -16.6), rightWrist: R(13.7, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 5.5), leftElbow: R(90.0, 0.0, -3.2), leftWrist: R(-13.2, 0.0, 0.0) } },
      { t: 29.195, pose: { rightShoulder: R(20.0, 0.0, 3.9), rightElbow: R(90.0, 0.0, 16.6), rightWrist: R(-6.0, 0.0, 0.0), leftShoulder: R(19.5, 0.0, 4.3), leftElbow: R(90.0, 0.0, -16.6), leftWrist: R(1.5, 0.0, 0.0) } },
      { t: 42.142, pose: { rightShoulder: R(8.2, 0.0, 3.0), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 12.7), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(21.1, 0.0, 0.0) } }
    ],
  },
  HEALTHY: {
    duration: 67.77,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-82.7, 0.0, 60.3), rightElbow: R(101.3, 0.0, 12.9), rightWrist: R(-0.2, 0.0, 0.0), leftShoulder: R(-76.1, 0.0, 150.2), leftElbow: R(76.2, 0.0, -25.2), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 33.967, pose: { rightShoulder: R(-43.4, 0.0, 8.8), rightElbow: R(18.7, 0.0, 3.2), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-28.7, 0.0, 13.0), leftElbow: R(32.5, 0.0, -3.2), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 65.365, pose: { rightShoulder: R(-18.0, 0.0, 35.4), rightElbow: R(53.9, 0.0, 6.5), rightWrist: R(-3.9, 0.0, 0.0), leftShoulder: R(-19.6, 0.0, 78.5), leftElbow: R(18.7, 0.0, -28.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 65.432, pose: { rightShoulder: R(-41.2, 0.0, 40.6), rightElbow: R(3.6, 0.0, -10.3), rightWrist: R(-2.8, 0.0, 0.0), leftShoulder: R(-48.8, 0.0, 115.7), leftElbow: R(-33.8, 0.0, -4.7), leftWrist: R(1.5, 0.0, 0.0) } },
      { t: 65.565, pose: { rightShoulder: R(-65.4, 0.0, 35.0), rightElbow: R(-37.1, 0.0, 34.5), rightWrist: R(-12.8, 0.0, 0.0), leftShoulder: R(-60.9, 0.0, 133.7), leftElbow: R(-37.1, 0.0, 6.2), leftWrist: R(-1.0, 0.0, 0.0) } },
      { t: 67.767, pose: { rightShoulder: R(20.2, 0.0, 6.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 5.4), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  HELLO: {
    duration: 11.14,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-73.0, 0.0, 22.3), rightElbow: R(101.3, 0.0, -57.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-74.7, 0.0, 7.7), leftElbow: R(90.0, 0.0, 57.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.035, pose: { rightShoulder: R(-19.6, 0.0, 51.7), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(-6.1, 0.0, 0.0), leftShoulder: R(-19.6, 0.0, 50.1), leftElbow: R(18.7, 0.0, -16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.101, pose: { rightShoulder: R(-40.4, 0.0, 55.9), rightElbow: R(-18.7, 0.0, -16.6), rightWrist: R(1.7, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 77.6), leftElbow: R(-18.7, 0.0, 16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.135, pose: { rightShoulder: R(-60.0, 0.0, 59.9), rightElbow: R(-53.9, 0.0, -47.9), rightWrist: R(9.2, 0.0, 0.0), leftShoulder: R(-60.0, 0.0, 104.2), leftElbow: R(-53.9, 0.0, 47.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 3.137, pose: { rightShoulder: R(-20.3, 0.0, 28.3), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(6.8, 0.0, 0.0), leftShoulder: R(-21.4, 0.0, 41.8), leftElbow: R(3.6, 0.0, -33.0), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 11.145, pose: { rightShoulder: R(20.0, 0.0, 8.3), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.7, 0.0, 4.1), leftElbow: R(79.9, 0.0, 84.5), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  HOME: {
    duration: 28.97,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-2.4, 0.0, 9.0), rightElbow: R(-62.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 7.5), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(-20.3, 0.0, 0.0) } },
      { t: 3.6, pose: { rightShoulder: R(3.0, 0.0, 8.8), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(11.8, 0.0, 16.9), leftElbow: R(51.4, 0.0, -80.0), leftWrist: R(-4.0, 0.0, 0.0) } },
      { t: 3.633, pose: { rightShoulder: R(1.6, 0.0, 8.8), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(8.2, 0.0, 16.5), leftElbow: R(19.9, 0.0, -80.0), leftWrist: R(-0.8, 0.0, 0.0) } },
      { t: 14.0, pose: { rightShoulder: R(15.5, 0.0, 10.5), rightElbow: R(82.9, 0.0, 80.0), rightWrist: R(6.4, 0.0, 0.0), leftShoulder: R(10.0, 0.0, 12.6), leftElbow: R(1.5, 0.0, -80.0), leftWrist: R(-6.2, 0.0, 0.0) } },
      { t: 14.5, pose: { rightShoulder: R(9.5, 0.0, 10.2), rightElbow: R(33.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(10.9, 0.0, 7.8), leftElbow: R(86.2, 0.0, -80.0), leftWrist: R(-6.9, 0.0, 0.0) } },
      { t: 28.966, pose: { rightShoulder: R(-14.7, 0.0, 8.9), rightElbow: R(-90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 14.8), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(21.4, 0.0, 0.0) } }
    ],
  },
  LIKE: {
    duration: 16.23,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(20.0, 0.0, 2.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(19.7, 0.0, 3.9), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 15.7, pose: { rightShoulder: R(5.9, 0.0, 4.5), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(1.0, 0.0, 0.0), leftShoulder: R(-9.1, 0.0, 6.9), leftElbow: R(-18.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 15.733, pose: { rightShoulder: R(-0.4, 0.0, 3.9), rightElbow: R(-33.8, 0.0, 80.0), rightWrist: R(-1.1, 0.0, 0.0), leftShoulder: R(-14.9, 0.0, 7.1), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 15.866, pose: { rightShoulder: R(1.0, 0.0, 2.7), rightElbow: R(-33.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-9.1, 0.0, 7.6), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 15.9, pose: { rightShoulder: R(7.8, 0.0, 2.4), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-0.4, 0.0, 7.7), leftElbow: R(-18.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 16.233, pose: { rightShoulder: R(18.6, 0.0, 2.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(16.9, 0.0, 6.9), leftElbow: R(67.3, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  LOVE: {
    duration: 55.32,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-3.6, 0.0, 3.1), rightElbow: R(-67.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(1.9, 0.0, 4.8), leftElbow: R(82.4, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.3, pose: { rightShoulder: R(-0.7, 0.0, 3.6), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(0.4, 0.0, 4.9), leftElbow: R(66.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 53.62, pose: { rightShoulder: R(2.4, 0.0, 12.8), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-7.3, 0.0, 10.8), leftElbow: R(-82.9, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 53.653, pose: { rightShoulder: R(5.6, 0.0, 12.4), rightElbow: R(53.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-4.5, 0.0, 10.3), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 53.686, pose: { rightShoulder: R(9.1, 0.0, 12.2), rightElbow: R(82.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-1.3, 0.0, 9.5), leftElbow: R(-3.6, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 55.321, pose: { rightShoulder: R(-2.1, 0.0, 6.0), rightElbow: R(-67.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 6.3), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(21.5, 0.0, 0.0) } }
    ],
  },
  ME: {
    duration: 93.43,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-4.3, 0.0, 13.5), rightElbow: R(-90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-5.1, 0.0, 12.5), leftElbow: R(-90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 68.443, pose: { rightShoulder: R(9.5, 0.0, 12.4), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(4.1, 0.0, 0.0), leftShoulder: R(7.5, 0.0, 16.6), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(-3.7, 0.0, 0.0) } },
      { t: 70.028, pose: { rightShoulder: R(2.8, 0.0, 11.7), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(-1.1, 0.0, 0.0), leftShoulder: R(2.1, 0.0, 12.2), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(-1.4, 0.0, 0.0) } },
      { t: 84.25, pose: { rightShoulder: R(-0.6, 0.0, 11.1), rightElbow: R(-53.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-0.5, 0.0, 9.0), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 84.292, pose: { rightShoulder: R(0.6, 0.0, 11.0), rightElbow: R(-3.6, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(0.3, 0.0, 9.0), leftElbow: R(-3.6, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 93.426, pose: { rightShoulder: R(1.6, 0.0, 11.6), rightElbow: R(14.5, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(0.1, 0.0, 9.8), leftElbow: R(14.5, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  MONEY: {
    duration: 90.62,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(7.4, 0.0, 14.8), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-7.4, 0.0, 13.7), leftElbow: R(-93.8, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 6.306, pose: { rightShoulder: R(20.0, 0.0, 10.5), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(20.4, 0.0, 0.0), leftShoulder: R(7.5, 0.0, 14.7), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(1.4, 0.0, 0.0) } },
      { t: 6.506, pose: { rightShoulder: R(20.0, 0.0, 17.5), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(20.8, 0.0, 0.0), leftShoulder: R(3.0, 0.0, 14.0), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 28.695, pose: { rightShoulder: R(20.0, 0.0, 25.0), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-22.0, 0.0, 0.0), leftShoulder: R(-0.6, 0.0, 10.0), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 90.59, pose: { rightShoulder: R(10.5, 0.0, 10.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(0.5, 0.0, 13.8), leftElbow: R(-84.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 90.623, pose: { rightShoulder: R(9.4, 0.0, 10.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-0.6, 0.0, 13.9), leftElbow: R(-134.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  NEED: {
    duration: 11.14,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-73.0, 0.0, 22.3), rightElbow: R(101.3, 0.0, -57.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-74.7, 0.0, 7.7), leftElbow: R(90.0, 0.0, 57.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.035, pose: { rightShoulder: R(-19.6, 0.0, 51.7), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(-6.1, 0.0, 0.0), leftShoulder: R(-19.6, 0.0, 50.1), leftElbow: R(18.7, 0.0, -16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.101, pose: { rightShoulder: R(-40.4, 0.0, 55.9), rightElbow: R(-18.7, 0.0, -16.6), rightWrist: R(1.7, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 77.6), leftElbow: R(-18.7, 0.0, 16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.135, pose: { rightShoulder: R(-60.0, 0.0, 59.9), rightElbow: R(-53.9, 0.0, -47.9), rightWrist: R(9.2, 0.0, 0.0), leftShoulder: R(-60.0, 0.0, 104.2), leftElbow: R(-53.9, 0.0, 47.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 3.137, pose: { rightShoulder: R(-20.3, 0.0, 28.3), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(6.8, 0.0, 0.0), leftShoulder: R(-21.4, 0.0, 41.8), leftElbow: R(3.6, 0.0, -33.0), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 11.145, pose: { rightShoulder: R(20.0, 0.0, 8.3), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.7, 0.0, 4.1), leftElbow: R(79.9, 0.0, 84.5), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  NO: {
    duration: 40.27,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(20.0, 0.0, 43.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.0, 0.0, 27.7), leftElbow: R(105.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 2.202, pose: { rightShoulder: R(11.8, 0.0, 41.2), rightElbow: R(-69.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(2.0, 0.0, 20.5), leftElbow: R(10.3, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 2.336, pose: { rightShoulder: R(8.0, 0.0, 38.1), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(11.4, 0.0, 34.4), leftElbow: R(64.4, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 2.402, pose: { rightShoulder: R(10.1, 0.0, 34.0), rightElbow: R(53.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.6, 0.0, 31.7), leftElbow: R(62.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 2.436, pose: { rightShoulder: R(10.4, 0.0, 31.8), rightElbow: R(82.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(2.0, 0.0, 25.6), leftElbow: R(1.5, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 40.274, pose: { rightShoulder: R(17.6, 0.0, 25.4), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(16.6, 0.0, 73.1), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  NOW: {
    duration: 10.64,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-20.0, 0.0, 6.4), rightElbow: R(-134.1, 0.0, 80.0), rightWrist: R(4.7, 0.0, 0.0), leftShoulder: R(-24.7, 0.0, 8.3), leftElbow: R(-130.3, 0.0, -80.0), leftWrist: R(-4.1, 0.0, 0.0) } },
      { t: 0.033, pose: { rightShoulder: R(-12.1, 0.0, 6.7), rightElbow: R(-84.7, 0.0, 80.0), rightWrist: R(0.5, 0.0, 0.0), leftShoulder: R(-16.4, 0.0, 8.9), leftElbow: R(-96.3, 0.0, -80.0), leftWrist: R(-0.6, 0.0, 0.0) } },
      { t: 0.066, pose: { rightShoulder: R(-5.0, 0.0, 7.0), rightElbow: R(-41.2, 0.0, 80.0), rightWrist: R(-2.5, 0.0, 0.0), leftShoulder: R(-8.9, 0.0, 9.3), leftElbow: R(-64.4, 0.0, -80.0), leftWrist: R(2.0, 0.0, 0.0) } },
      { t: 10.31, pose: { rightShoulder: R(8.0, 0.0, 8.9), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(1.8, 0.0, 0.0), leftShoulder: R(2.7, 0.0, 8.5), leftElbow: R(-18.7, 0.0, -80.0), leftWrist: R(-3.2, 0.0, 0.0) } },
      { t: 10.343, pose: { rightShoulder: R(2.1, 0.0, 9.0), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(1.4, 0.0, 0.0), leftShoulder: R(-3.8, 0.0, 9.1), leftElbow: R(-53.9, 0.0, -80.0), leftWrist: R(-3.9, 0.0, 0.0) } },
      { t: 10.643, pose: { rightShoulder: R(-16.9, 0.0, 8.2), rightElbow: R(-67.3, 0.0, 80.0), rightWrist: R(0.3, 0.0, 0.0), leftShoulder: R(-20.2, 0.0, 8.7), leftElbow: R(-90.0, 0.0, -80.0), leftWrist: R(-1.9, 0.0, 0.0) } }
    ],
  },
  PHONE: {
    duration: 55.62,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(2.2, 0.0, 7.6), rightElbow: R(90.0, 0.0, -85.6), rightWrist: R(-3.8, 0.0, 0.0), leftShoulder: R(-3.3, 0.0, 9.4), leftElbow: R(22.0, 0.0, -80.0), leftWrist: R(2.1, 0.0, 0.0) } },
      { t: 5.572, pose: { rightShoulder: R(6.0, 0.0, 9.1), rightElbow: R(18.7, 0.0, 3.2), rightWrist: R(3.0, 0.0, 0.0), leftShoulder: R(0.8, 0.0, 13.2), leftElbow: R(35.5, 0.0, -47.9), leftWrist: R(-10.4, 0.0, 0.0) } },
      { t: 20.32, pose: { rightShoulder: R(-19.5, 0.0, 21.2), rightElbow: R(53.9, 0.0, 9.1), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-45.8, 0.0, 75.9), leftElbow: R(101.3, 0.0, -9.1), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.354, pose: { rightShoulder: R(-25.5, 0.0, 16.1), rightElbow: R(3.6, 0.0, -16.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-63.9, 0.0, 101.1), leftElbow: R(82.9, 0.0, 30.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.587, pose: { rightShoulder: R(-37.9, 0.0, 47.6), rightElbow: R(82.9, 0.0, -16.6), rightWrist: R(5.0, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 120.1), leftElbow: R(38.8, 0.0, -0.2), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 55.622, pose: { rightShoulder: R(-30.5, 0.0, 33.9), rightElbow: R(-13.2, 0.0, -69.9), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(5.2, 0.0, 56.0), leftElbow: R(-32.1, 0.0, 8.4), leftWrist: R(1.9, 0.0, 0.0) } }
    ],
  },
  SAD: {
    duration: 9.41,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-13.6, 0.0, 4.2), rightElbow: R(-64.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-8.0, 0.0, 6.1), leftElbow: R(-76.2, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.233, pose: { rightShoulder: R(-7.7, 0.0, 4.4), rightElbow: R(-53.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-0.6, 0.0, 7.1), leftElbow: R(-18.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.266, pose: { rightShoulder: R(-1.0, 0.0, 4.8), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(5.5, 0.0, 7.6), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.3, pose: { rightShoulder: R(6.0, 0.0, 5.3), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(11.6, 0.0, 8.1), leftElbow: R(53.9, 0.0, -80.0), leftWrist: R(1.5, 0.0, 0.0) } },
      { t: 9.142, pose: { rightShoulder: R(1.6, 0.0, 7.8), rightElbow: R(-16.6, 0.0, 80.0), rightWrist: R(-1.3, 0.0, 0.0), leftShoulder: R(3.9, 0.0, 8.0), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(1.3, 0.0, 0.0) } },
      { t: 9.409, pose: { rightShoulder: R(-9.3, 0.0, 6.3), rightElbow: R(-78.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-6.4, 0.0, 7.0), leftElbow: R(-76.2, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  SCHOOL: {
    duration: 15.23,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(2.1, 0.0, 5.5), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(10.5, 0.0, 7.1), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.766, pose: { rightShoulder: R(8.4, 0.0, 4.2), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(6.0, 0.0, 6.1), leftElbow: R(86.2, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.8, pose: { rightShoulder: R(8.9, 0.0, 4.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(9.8, 0.0, 6.2), leftElbow: R(105.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 14.133, pose: { rightShoulder: R(21.8, 0.0, 3.8), rightElbow: R(105.1, 0.0, 80.0), rightWrist: R(-20.5, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 3.3), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(-8.4, 0.0, 0.0) } },
      { t: 14.166, pose: { rightShoulder: R(20.6, 0.0, 4.4), rightElbow: R(86.2, 0.0, 80.0), rightWrist: R(-19.7, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 4.5), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(-4.2, 0.0, 0.0) } },
      { t: 15.233, pose: { rightShoulder: R(16.7, 0.0, 3.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 7.5), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  SORRY: {
    duration: 39.81,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-13.2, 0.0, 1.9), rightElbow: R(90.0, 0.0, -55.4), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-40.1, 0.0, 5.2), leftElbow: R(-14.5, 0.0, 106.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.034, pose: { rightShoulder: R(-6.3, 0.0, 3.2), rightElbow: R(90.0, 0.0, -23.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-25.6, 0.0, 10.9), leftElbow: R(22.0, 0.0, 55.8), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.067, pose: { rightShoulder: R(-0.2, 0.0, 4.3), rightElbow: R(90.0, 0.0, 3.7), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-13.0, 0.0, 15.5), leftElbow: R(52.2, 0.0, 12.3), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 39.74, pose: { rightShoulder: R(-65.6, 0.0, 44.0), rightElbow: R(-13.8, 0.0, 80.0), rightWrist: R(3.6, 0.0, 0.0), leftShoulder: R(-72.7, 0.0, 44.4), leftElbow: R(82.2, 0.0, -51.7), leftWrist: R(-1.4, 0.0, 0.0) } },
      { t: 39.774, pose: { rightShoulder: R(-83.4, 0.0, 56.4), rightElbow: R(-62.8, 0.0, 80.0), rightWrist: R(2.5, 0.0, 0.0), leftShoulder: R(-80.8, 0.0, 65.7), leftElbow: R(94.3, 0.0, -78.0), leftWrist: R(0.1, 0.0, 0.0) } },
      { t: 39.807, pose: { rightShoulder: R(-102.4, 0.0, 70.8), rightElbow: R(-120.2, 0.0, 80.0), rightWrist: R(0.1, 0.0, 0.0), leftShoulder: R(-87.7, 0.0, 91.2), leftElbow: R(108.9, 0.0, -111.3), leftWrist: R(2.0, 0.0, 0.0) } }
    ],
  },
  THANK_YOU: {
    duration: 11.88,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(20.0, 0.0, 35.7), rightElbow: R(-14.5, 0.0, 80.0), rightWrist: R(0.6, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 58.1), leftElbow: R(-14.5, 0.0, 12.9), leftWrist: R(-4.3, 0.0, 0.0) } },
      { t: 2.72, pose: { rightShoulder: R(20.0, 0.0, 26.4), rightElbow: R(22.0, 0.0, 80.0), rightWrist: R(3.1, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 39.7), leftElbow: R(22.0, 0.0, -19.6), leftWrist: R(0.3, 0.0, 0.0) } },
      { t: 2.76, pose: { rightShoulder: R(20.0, 0.0, 18.9), rightElbow: R(52.2, 0.0, 80.0), rightWrist: R(5.5, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 24.6), leftElbow: R(52.2, 0.0, -46.4), leftWrist: R(3.9, 0.0, 0.0) } },
      { t: 2.8, pose: { rightShoulder: R(20.0, 0.0, 13.0), rightElbow: R(76.2, 0.0, 80.0), rightWrist: R(7.8, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 12.8), leftElbow: R(76.2, 0.0, -67.7), leftWrist: R(6.5, 0.0, 0.0) } },
      { t: 2.84, pose: { rightShoulder: R(20.0, 0.0, 9.0), rightElbow: R(93.8, 0.0, 80.0), rightWrist: R(10.0, 0.0, 0.0), leftShoulder: R(20.0, 0.0, 4.3), leftElbow: R(93.8, 0.0, -83.4), leftWrist: R(8.2, 0.0, 0.0) } },
      { t: 11.88, pose: { rightShoulder: R(14.0, 0.0, 16.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(19.4, 0.0, 0.0), leftShoulder: R(9.7, 0.0, 13.6), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  THEY: {
    duration: 49.82,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(0.7, 0.0, 4.5), rightElbow: R(-14.5, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(2.0, 0.0, 7.8), leftElbow: R(-14.5, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.033, pose: { rightShoulder: R(3.0, 0.0, 4.9), rightElbow: R(22.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(2.2, 0.0, 7.3), leftElbow: R(22.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 9.776, pose: { rightShoulder: R(11.4, 0.0, 16.7), rightElbow: R(3.6, 0.0, 80.0), rightWrist: R(-8.7, 0.0, 0.0), leftShoulder: R(4.0, 0.0, 5.4), leftElbow: R(105.1, 0.0, -80.0), leftWrist: R(3.8, 0.0, 0.0) } },
      { t: 35.936, pose: { rightShoulder: R(21.3, 0.0, 26.1), rightElbow: R(105.1, 0.0, 80.0), rightWrist: R(-15.2, 0.0, 0.0), leftShoulder: R(1.7, 0.0, 5.8), leftElbow: R(18.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 35.969, pose: { rightShoulder: R(18.4, 0.0, 23.4), rightElbow: R(86.2, 0.0, 80.0), rightWrist: R(-12.7, 0.0, 0.0), leftShoulder: R(-1.4, 0.0, 6.1), leftElbow: R(-33.8, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 49.816, pose: { rightShoulder: R(15.0, 0.0, 2.2), rightElbow: R(132.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(14.4, 0.0, 9.9), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  TIRED: {
    duration: 9.88,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-21.5, 0.0, 4.6), rightElbow: R(-130.3, 0.0, 80.0), rightWrist: R(1.6, 0.0, 0.0), leftShoulder: R(-8.5, 0.0, 6.8), leftElbow: R(-134.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.033, pose: { rightShoulder: R(-14.3, 0.0, 5.7), rightElbow: R(-96.3, 0.0, 80.0), rightWrist: R(0.2, 0.0, 0.0), leftShoulder: R(-3.0, 0.0, 8.2), leftElbow: R(-84.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.066, pose: { rightShoulder: R(-7.6, 0.0, 7.3), rightElbow: R(-64.4, 0.0, 80.0), rightWrist: R(-0.8, 0.0, 0.0), leftShoulder: R(1.9, 0.0, 10.0), leftElbow: R(-41.2, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 9.476, pose: { rightShoulder: R(0.5, 0.0, 17.8), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(0.8, 0.0, 0.0), leftShoulder: R(12.8, 0.0, 13.1), leftElbow: R(53.9, 0.0, -80.0), leftWrist: R(1.3, 0.0, 0.0) } },
      { t: 9.509, pose: { rightShoulder: R(-6.6, 0.0, 16.6), rightElbow: R(-53.9, 0.0, 80.0), rightWrist: R(-1.4, 0.0, 0.0), leftShoulder: R(8.0, 0.0, 10.8), leftElbow: R(3.6, 0.0, -80.0), leftWrist: R(1.8, 0.0, 0.0) } },
      { t: 9.876, pose: { rightShoulder: R(2.3, 0.0, 5.5), rightElbow: R(134.1, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(5.9, 0.0, 5.3), leftElbow: R(95.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  TODAY: {
    duration: 95.46,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(15.7, 0.0, -2.0), rightElbow: R(67.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(21.4, 0.0, -14.4), leftElbow: R(90.0, 0.0, -19.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.333, pose: { rightShoulder: R(12.6, 0.0, 26.8), rightElbow: R(10.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(6.6, 0.0, 6.3), leftElbow: R(105.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.367, pose: { rightShoulder: R(9.6, 0.0, 20.2), rightElbow: R(-33.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.4, 0.0, -5.8), leftElbow: R(86.2, 0.0, -93.4), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 34.067, pose: { rightShoulder: R(18.5, 0.0, 3.5), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-0.9, 0.0, 0.0), leftShoulder: R(7.3, 0.0, 2.3), leftElbow: R(53.9, 0.0, -16.6), leftWrist: R(4.5, 0.0, 0.0) } },
      { t: 34.1, pose: { rightShoulder: R(17.2, 0.0, 4.4), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-0.4, 0.0, 0.0), leftShoulder: R(1.7, 0.0, 3.0), leftElbow: R(3.6, 0.0, -47.9), leftWrist: R(0.9, 0.0, 0.0) } },
      { t: 95.462, pose: { rightShoulder: R(20.0, 0.0, 39.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-28.0, 0.0, 0.0), leftShoulder: R(19.6, 0.0, 1.8), leftElbow: R(90.0, 0.0, -83.4), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  TOMORROW: {
    duration: 95.46,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(15.7, 0.0, -2.0), rightElbow: R(67.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(21.4, 0.0, -14.4), leftElbow: R(90.0, 0.0, -19.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.333, pose: { rightShoulder: R(12.6, 0.0, 26.8), rightElbow: R(10.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(6.6, 0.0, 6.3), leftElbow: R(105.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.367, pose: { rightShoulder: R(9.6, 0.0, 20.2), rightElbow: R(-33.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.4, 0.0, -5.8), leftElbow: R(86.2, 0.0, -93.4), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 34.067, pose: { rightShoulder: R(18.5, 0.0, 3.5), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-0.9, 0.0, 0.0), leftShoulder: R(7.3, 0.0, 2.3), leftElbow: R(53.9, 0.0, -16.6), leftWrist: R(4.5, 0.0, 0.0) } },
      { t: 34.1, pose: { rightShoulder: R(17.2, 0.0, 4.4), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-0.4, 0.0, 0.0), leftShoulder: R(1.7, 0.0, 3.0), leftElbow: R(3.6, 0.0, -47.9), leftWrist: R(0.9, 0.0, 0.0) } },
      { t: 95.462, pose: { rightShoulder: R(20.0, 0.0, 39.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-28.0, 0.0, 0.0), leftShoulder: R(19.6, 0.0, 1.8), leftElbow: R(90.0, 0.0, -83.4), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  WANT: {
    duration: 20.87,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(18.3, 0.0, 2.7), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(9.3, 0.0, 6.3), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 8.3, pose: { rightShoulder: R(20.0, 0.0, 4.1), rightElbow: R(90.0, 0.0, 93.4), rightWrist: R(14.1, 0.0, 0.0), leftShoulder: R(19.3, 0.0, 2.3), leftElbow: R(90.0, 0.0, -42.3), leftWrist: R(-9.9, 0.0, 0.0) } },
      { t: 8.333, pose: { rightShoulder: R(19.9, 0.0, 3.3), rightElbow: R(90.0, 0.0, 76.6), rightWrist: R(8.2, 0.0, 0.0), leftShoulder: R(18.8, 0.0, 1.7), leftElbow: R(90.0, 0.0, -1.3), leftWrist: R(-3.0, 0.0, 0.0) } },
      { t: 8.566, pose: { rightShoulder: R(19.6, 0.0, 0.7), rightElbow: R(90.0, 0.0, 63.6), rightWrist: R(-7.9, 0.0, 0.0), leftShoulder: R(20.5, 0.0, 1.4), leftElbow: R(90.0, 0.0, -73.7), leftWrist: R(13.0, 0.0, 0.0) } },
      { t: 16.1, pose: { rightShoulder: R(20.0, 0.0, 2.8), rightElbow: R(90.0, 0.0, 16.6), rightWrist: R(-11.8, 0.0, 0.0), leftShoulder: R(20.5, 0.0, 7.6), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(2.5, 0.0, 0.0) } },
      { t: 20.866, pose: { rightShoulder: R(13.1, 0.0, 2.3), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(6.5, 0.0, 5.6), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  WATER: {
    duration: 7.17,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-24.9, 0.0, 7.3), rightElbow: R(-134.1, 0.0, 80.0), rightWrist: R(-2.0, 0.0, 0.0), leftShoulder: R(-5.4, 0.0, 5.7), leftElbow: R(-119.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.033, pose: { rightShoulder: R(-15.9, 0.0, 7.0), rightElbow: R(-84.7, 0.0, 80.0), rightWrist: R(0.1, 0.0, 0.0), leftShoulder: R(-4.1, 0.0, 5.7), leftElbow: R(-91.8, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.066, pose: { rightShoulder: R(-7.9, 0.0, 7.2), rightElbow: R(-41.2, 0.0, 80.0), rightWrist: R(1.4, 0.0, 0.0), leftShoulder: R(-2.9, 0.0, 5.7), leftElbow: R(-66.3, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.1, pose: { rightShoulder: R(-0.8, 0.0, 7.7), rightElbow: R(-3.7, 0.0, 80.0), rightWrist: R(1.9, 0.0, 0.0), leftShoulder: R(-1.8, 0.0, 5.7), leftElbow: R(-42.4, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 6.973, pose: { rightShoulder: R(15.0, 0.0, 17.0), rightElbow: R(53.9, 0.0, 80.0), rightWrist: R(1.2, 0.0, 0.0), leftShoulder: R(6.0, 0.0, 5.2), leftElbow: R(38.8, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 7.173, pose: { rightShoulder: R(-11.6, 0.0, 12.0), rightElbow: R(-130.3, 0.0, 80.0), rightWrist: R(-2.5, 0.0, 0.0), leftShoulder: R(-2.2, 0.0, 5.6), leftElbow: R(-62.3, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  WE: {
    duration: 55.62,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(2.2, 0.0, 7.6), rightElbow: R(90.0, 0.0, -85.6), rightWrist: R(-3.8, 0.0, 0.0), leftShoulder: R(-3.3, 0.0, 9.4), leftElbow: R(22.0, 0.0, -80.0), leftWrist: R(2.1, 0.0, 0.0) } },
      { t: 5.572, pose: { rightShoulder: R(6.0, 0.0, 9.1), rightElbow: R(18.7, 0.0, 3.2), rightWrist: R(3.0, 0.0, 0.0), leftShoulder: R(0.8, 0.0, 13.2), leftElbow: R(35.5, 0.0, -47.9), leftWrist: R(-10.4, 0.0, 0.0) } },
      { t: 20.32, pose: { rightShoulder: R(-19.5, 0.0, 21.2), rightElbow: R(53.9, 0.0, 9.1), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-45.8, 0.0, 75.9), leftElbow: R(101.3, 0.0, -9.1), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.354, pose: { rightShoulder: R(-25.5, 0.0, 16.1), rightElbow: R(3.6, 0.0, -16.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-63.9, 0.0, 101.1), leftElbow: R(82.9, 0.0, 30.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.587, pose: { rightShoulder: R(-37.9, 0.0, 47.6), rightElbow: R(82.9, 0.0, -16.6), rightWrist: R(5.0, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 120.1), leftElbow: R(38.8, 0.0, -0.2), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 55.622, pose: { rightShoulder: R(-30.5, 0.0, 33.9), rightElbow: R(-13.2, 0.0, -69.9), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(5.2, 0.0, 56.0), leftElbow: R(-32.1, 0.0, 8.4), leftWrist: R(1.9, 0.0, 0.0) } }
    ],
  },
  WHAT: {
    duration: 11.14,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-73.0, 0.0, 22.3), rightElbow: R(101.3, 0.0, -57.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-74.7, 0.0, 7.7), leftElbow: R(90.0, 0.0, 57.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.035, pose: { rightShoulder: R(-19.6, 0.0, 51.7), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(-6.1, 0.0, 0.0), leftShoulder: R(-19.6, 0.0, 50.1), leftElbow: R(18.7, 0.0, -16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.101, pose: { rightShoulder: R(-40.4, 0.0, 55.9), rightElbow: R(-18.7, 0.0, -16.6), rightWrist: R(1.7, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 77.6), leftElbow: R(-18.7, 0.0, 16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.135, pose: { rightShoulder: R(-60.0, 0.0, 59.9), rightElbow: R(-53.9, 0.0, -47.9), rightWrist: R(9.2, 0.0, 0.0), leftShoulder: R(-60.0, 0.0, 104.2), leftElbow: R(-53.9, 0.0, 47.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 3.137, pose: { rightShoulder: R(-20.3, 0.0, 28.3), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(6.8, 0.0, 0.0), leftShoulder: R(-21.4, 0.0, 41.8), leftElbow: R(3.6, 0.0, -33.0), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 11.145, pose: { rightShoulder: R(20.0, 0.0, 8.3), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.7, 0.0, 4.1), leftElbow: R(79.9, 0.0, 84.5), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  WHEN: {
    duration: 11.14,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-73.0, 0.0, 22.3), rightElbow: R(101.3, 0.0, -57.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-74.7, 0.0, 7.7), leftElbow: R(90.0, 0.0, 57.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.035, pose: { rightShoulder: R(-19.6, 0.0, 51.7), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(-6.1, 0.0, 0.0), leftShoulder: R(-19.6, 0.0, 50.1), leftElbow: R(18.7, 0.0, -16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.101, pose: { rightShoulder: R(-40.4, 0.0, 55.9), rightElbow: R(-18.7, 0.0, -16.6), rightWrist: R(1.7, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 77.6), leftElbow: R(-18.7, 0.0, 16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.135, pose: { rightShoulder: R(-60.0, 0.0, 59.9), rightElbow: R(-53.9, 0.0, -47.9), rightWrist: R(9.2, 0.0, 0.0), leftShoulder: R(-60.0, 0.0, 104.2), leftElbow: R(-53.9, 0.0, 47.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 3.137, pose: { rightShoulder: R(-20.3, 0.0, 28.3), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(6.8, 0.0, 0.0), leftShoulder: R(-21.4, 0.0, 41.8), leftElbow: R(3.6, 0.0, -33.0), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 11.145, pose: { rightShoulder: R(20.0, 0.0, 8.3), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.7, 0.0, 4.1), leftElbow: R(79.9, 0.0, 84.5), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  WHERE: {
    duration: 55.62,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(2.2, 0.0, 7.6), rightElbow: R(90.0, 0.0, -85.6), rightWrist: R(-3.8, 0.0, 0.0), leftShoulder: R(-3.3, 0.0, 9.4), leftElbow: R(22.0, 0.0, -80.0), leftWrist: R(2.1, 0.0, 0.0) } },
      { t: 5.572, pose: { rightShoulder: R(6.0, 0.0, 9.1), rightElbow: R(18.7, 0.0, 3.2), rightWrist: R(3.0, 0.0, 0.0), leftShoulder: R(0.8, 0.0, 13.2), leftElbow: R(35.5, 0.0, -47.9), leftWrist: R(-10.4, 0.0, 0.0) } },
      { t: 20.32, pose: { rightShoulder: R(-19.5, 0.0, 21.2), rightElbow: R(53.9, 0.0, 9.1), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-45.8, 0.0, 75.9), leftElbow: R(101.3, 0.0, -9.1), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.354, pose: { rightShoulder: R(-25.5, 0.0, 16.1), rightElbow: R(3.6, 0.0, -16.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-63.9, 0.0, 101.1), leftElbow: R(82.9, 0.0, 30.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.587, pose: { rightShoulder: R(-37.9, 0.0, 47.6), rightElbow: R(82.9, 0.0, -16.6), rightWrist: R(5.0, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 120.1), leftElbow: R(38.8, 0.0, -0.2), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 55.622, pose: { rightShoulder: R(-30.5, 0.0, 33.9), rightElbow: R(-13.2, 0.0, -69.9), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(5.2, 0.0, 56.0), leftElbow: R(-32.1, 0.0, 8.4), leftWrist: R(1.9, 0.0, 0.0) } }
    ],
  },
  WHO: {
    duration: 55.62,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(2.2, 0.0, 7.6), rightElbow: R(90.0, 0.0, -85.6), rightWrist: R(-3.8, 0.0, 0.0), leftShoulder: R(-3.3, 0.0, 9.4), leftElbow: R(22.0, 0.0, -80.0), leftWrist: R(2.1, 0.0, 0.0) } },
      { t: 5.572, pose: { rightShoulder: R(6.0, 0.0, 9.1), rightElbow: R(18.7, 0.0, 3.2), rightWrist: R(3.0, 0.0, 0.0), leftShoulder: R(0.8, 0.0, 13.2), leftElbow: R(35.5, 0.0, -47.9), leftWrist: R(-10.4, 0.0, 0.0) } },
      { t: 20.32, pose: { rightShoulder: R(-19.5, 0.0, 21.2), rightElbow: R(53.9, 0.0, 9.1), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-45.8, 0.0, 75.9), leftElbow: R(101.3, 0.0, -9.1), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.354, pose: { rightShoulder: R(-25.5, 0.0, 16.1), rightElbow: R(3.6, 0.0, -16.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-63.9, 0.0, 101.1), leftElbow: R(82.9, 0.0, 30.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.587, pose: { rightShoulder: R(-37.9, 0.0, 47.6), rightElbow: R(82.9, 0.0, -16.6), rightWrist: R(5.0, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 120.1), leftElbow: R(38.8, 0.0, -0.2), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 55.622, pose: { rightShoulder: R(-30.5, 0.0, 33.9), rightElbow: R(-13.2, 0.0, -69.9), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(5.2, 0.0, 56.0), leftElbow: R(-32.1, 0.0, 8.4), leftWrist: R(1.9, 0.0, 0.0) } }
    ],
  },
  WHY: {
    duration: 55.62,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(2.2, 0.0, 7.6), rightElbow: R(90.0, 0.0, -85.6), rightWrist: R(-3.8, 0.0, 0.0), leftShoulder: R(-3.3, 0.0, 9.4), leftElbow: R(22.0, 0.0, -80.0), leftWrist: R(2.1, 0.0, 0.0) } },
      { t: 5.572, pose: { rightShoulder: R(6.0, 0.0, 9.1), rightElbow: R(18.7, 0.0, 3.2), rightWrist: R(3.0, 0.0, 0.0), leftShoulder: R(0.8, 0.0, 13.2), leftElbow: R(35.5, 0.0, -47.9), leftWrist: R(-10.4, 0.0, 0.0) } },
      { t: 20.32, pose: { rightShoulder: R(-19.5, 0.0, 21.2), rightElbow: R(53.9, 0.0, 9.1), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-45.8, 0.0, 75.9), leftElbow: R(101.3, 0.0, -9.1), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.354, pose: { rightShoulder: R(-25.5, 0.0, 16.1), rightElbow: R(3.6, 0.0, -16.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-63.9, 0.0, 101.1), leftElbow: R(82.9, 0.0, 30.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 20.587, pose: { rightShoulder: R(-37.9, 0.0, 47.6), rightElbow: R(82.9, 0.0, -16.6), rightWrist: R(5.0, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 120.1), leftElbow: R(38.8, 0.0, -0.2), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 55.622, pose: { rightShoulder: R(-30.5, 0.0, 33.9), rightElbow: R(-13.2, 0.0, -69.9), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(5.2, 0.0, 56.0), leftElbow: R(-32.1, 0.0, 8.4), leftWrist: R(1.9, 0.0, 0.0) } }
    ],
  },
  WORK: {
    duration: 8.68,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-20.3, 0.0, 8.1), rightElbow: R(-134.1, 0.0, 80.0), rightWrist: R(-2.6, 0.0, 0.0), leftShoulder: R(-13.5, 0.0, 6.3), leftElbow: R(-134.1, 0.0, -80.0), leftWrist: R(3.0, 0.0, 0.0) } },
      { t: 0.033, pose: { rightShoulder: R(-12.0, 0.0, 5.9), rightElbow: R(-84.7, 0.0, 80.0), rightWrist: R(-0.3, 0.0, 0.0), leftShoulder: R(-7.3, 0.0, 7.8), leftElbow: R(-84.7, 0.0, -80.0), leftWrist: R(2.1, 0.0, 0.0) } },
      { t: 8.308, pose: { rightShoulder: R(8.0, 0.0, 16.2), rightElbow: R(18.7, 0.0, 80.0), rightWrist: R(9.4, 0.0, 0.0), leftShoulder: R(16.4, 0.0, 11.9), leftElbow: R(82.9, 0.0, -16.6), leftWrist: R(-10.4, 0.0, 0.0) } },
      { t: 8.341, pose: { rightShoulder: R(1.4, 0.0, 13.6), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(7.4, 0.0, 0.0), leftShoulder: R(12.1, 0.0, 10.6), leftElbow: R(53.9, 0.0, 30.0), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 8.375, pose: { rightShoulder: R(-4.8, 0.0, 11.7), rightElbow: R(-53.9, 0.0, 80.0), rightWrist: R(2.7, 0.0, 0.0), leftShoulder: R(7.7, 0.0, 8.7), leftElbow: R(18.7, 0.0, 58.0), leftWrist: R(-1.1, 0.0, 0.0) } },
      { t: 8.675, pose: { rightShoulder: R(-6.4, 0.0, 8.9), rightElbow: R(-90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(2.1, 0.0, 7.2), leftElbow: R(-64.8, 0.0, -102.4), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  YES: {
    duration: 40.27,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(20.0, 0.0, 43.1), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.0, 0.0, 27.7), leftElbow: R(105.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 2.202, pose: { rightShoulder: R(11.8, 0.0, 41.2), rightElbow: R(-69.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(2.0, 0.0, 20.5), leftElbow: R(10.3, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 2.336, pose: { rightShoulder: R(8.0, 0.0, 38.1), rightElbow: R(-18.7, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(11.4, 0.0, 34.4), leftElbow: R(64.4, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 2.402, pose: { rightShoulder: R(10.1, 0.0, 34.0), rightElbow: R(53.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.6, 0.0, 31.7), leftElbow: R(62.7, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 2.436, pose: { rightShoulder: R(10.4, 0.0, 31.8), rightElbow: R(82.9, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(2.0, 0.0, 25.6), leftElbow: R(1.5, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 40.274, pose: { rightShoulder: R(17.6, 0.0, 25.4), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(16.6, 0.0, 73.1), leftElbow: R(90.0, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  YESTERDAY: {
    duration: 95.46,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(15.7, 0.0, -2.0), rightElbow: R(67.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(21.4, 0.0, -14.4), leftElbow: R(90.0, 0.0, -19.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.333, pose: { rightShoulder: R(12.6, 0.0, 26.8), rightElbow: R(10.3, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(6.6, 0.0, 6.3), leftElbow: R(105.1, 0.0, -80.0), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 0.367, pose: { rightShoulder: R(9.6, 0.0, 20.2), rightElbow: R(-33.8, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.4, 0.0, -5.8), leftElbow: R(86.2, 0.0, -93.4), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 34.067, pose: { rightShoulder: R(18.5, 0.0, 3.5), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-0.9, 0.0, 0.0), leftShoulder: R(7.3, 0.0, 2.3), leftElbow: R(53.9, 0.0, -16.6), leftWrist: R(4.5, 0.0, 0.0) } },
      { t: 34.1, pose: { rightShoulder: R(17.2, 0.0, 4.4), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-0.4, 0.0, 0.0), leftShoulder: R(1.7, 0.0, 3.0), leftElbow: R(3.6, 0.0, -47.9), leftWrist: R(0.9, 0.0, 0.0) } },
      { t: 95.462, pose: { rightShoulder: R(20.0, 0.0, 39.9), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(-28.0, 0.0, 0.0), leftShoulder: R(19.6, 0.0, 1.8), leftElbow: R(90.0, 0.0, -83.4), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
  YOU: {
    duration: 11.14,
    frames: [
      { t: 0.0, pose: { rightShoulder: R(-73.0, 0.0, 22.3), rightElbow: R(101.3, 0.0, -57.6), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(-74.7, 0.0, 7.7), leftElbow: R(90.0, 0.0, 57.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.035, pose: { rightShoulder: R(-19.6, 0.0, 51.7), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(-6.1, 0.0, 0.0), leftShoulder: R(-19.6, 0.0, 50.1), leftElbow: R(18.7, 0.0, -16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.101, pose: { rightShoulder: R(-40.4, 0.0, 55.9), rightElbow: R(-18.7, 0.0, -16.6), rightWrist: R(1.7, 0.0, 0.0), leftShoulder: R(-40.4, 0.0, 77.6), leftElbow: R(-18.7, 0.0, 16.6), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 1.135, pose: { rightShoulder: R(-60.0, 0.0, 59.9), rightElbow: R(-53.9, 0.0, -47.9), rightWrist: R(9.2, 0.0, 0.0), leftShoulder: R(-60.0, 0.0, 104.2), leftElbow: R(-53.9, 0.0, 47.9), leftWrist: R(0.0, 0.0, 0.0) } },
      { t: 3.137, pose: { rightShoulder: R(-20.3, 0.0, 28.3), rightElbow: R(18.7, 0.0, 16.6), rightWrist: R(6.8, 0.0, 0.0), leftShoulder: R(-21.4, 0.0, 41.8), leftElbow: R(3.6, 0.0, -33.0), leftWrist: R(-6.0, 0.0, 0.0) } },
      { t: 11.145, pose: { rightShoulder: R(20.0, 0.0, 8.3), rightElbow: R(90.0, 0.0, 80.0), rightWrist: R(0.0, 0.0, 0.0), leftShoulder: R(13.7, 0.0, 4.1), leftElbow: R(79.9, 0.0, 84.5), leftWrist: R(0.0, 0.0, 0.0) } }
    ],
  },
}
